### ISSUE TITLE
Sub-tasks making up a Group task not returning their result as expected

### ISSUE THREAD

**Issue by anirvan-majumdar** [celery/celery#5334]
# Checklist

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have tried reproducing the issue on more than one message broker and/or result backend.
- [x] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with retries, ETA/Countdown & rate limits disabled.

## Environment & Settings
**Celery version**: `3.1.19`
**Report**:
<details>
```
```
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 2.7.10
* **Minimal Broker Version**: RabbitMQ 3.6.1
* **Minimal Result Backend Version**: MySQL 5.6.24
* **Minimal OS and/or Kernel Version**: : Ubuntu/MacOS

### Python Packages

<details>
```
django-celery           3.1.17
Django                  1.7
celery                  3.1.19
```
</details>

### Other Dependencies

<details>
N/A
</details>

## Minimally Reproducible Test Case

Hi — I am trying to deploy a `Group` based task flow in my Django application and for that, I was trying to familiarise myself with the construct.

In the code snippet below, there are 3 tasks: `A` --- which calls ---> `B` (in a group) --- which calls --> `C` (to compute the square of a number).

Since the method `A` is also invoked asynchronously (executed on the default `celery` queue) — I made sure to invoke every instance of task `B` on a separate queue (`processor`) to avoid deadlocks. The rest of the code is fairly self-explanatory. 

From a Django shell, I invoke `A` like so:
```A.delay(10)```

```python

@task()
def A(num):
    import time
    job = group(B.s(i).set(queue='processor') for i in range(num))
    job_result = job.apply_async()
    while not job_result.ready():
        time.sleep(1)
    print "---------------------"
    results = job_result.get()
    print "Total results: {}".format(len(results))
    for result in results:
        if result.ready() and result.successful():
            print "Result:: {}".format(result.get())
        else:
            print "FAILED:: {}".format(result)


@task()
def B(i):
    return pow2.delay(i)


@task()
def pow2(i):
    return i ** 2

```

# Expected Behavior

In the above code, I was expecting that the result for each of the sub-tasks making up the Group would be printed at the end.

# Actual Behavior

In reality however, there would invariably be some or the other sub-task that would not get completed and would only return its result value _after_ the group resultset values have been printed. Sometimes though, all the sub-tasks would return. But there's no surety of what would happen. I was hoping to use this approach to parallelise a big task which is currently run by a single worker and then collate the results. 

Here are some of the sample output of running the code above:

**Log Sample 1**

```
[2019-02-12 04:53:14,891: INFO/MainProcess] Received task: apiserver.tasks.A[6820f648-6e68-4cb8-85e5-0ba996531003]
[2019-02-12 04:53:15,140: INFO/MainProcess] Received task: apiserver.tasks.pow2[227482ce-a60f-455f-956e-af2a1a8fc61a]
[2019-02-12 04:53:15,148: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[227482ce
[2019-02-12 04:53:15,154: INFO/MainProcess] Received task: apiserver.tasks.pow2[0bc9e985-8270-43f2-9062-5b61aa409531]
[2019-02-12 04:53:15,178: INFO/MainProcess] Received task: apiserver.tasks.pow2[85a156f2-e090-4725-b3e1-a09fa56f5bb9]
[2019-02-12 04:53:15,202: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[85a156f2-e090-4725-b3e1-a09fa56f5bb9] succeeded in 0.00847279899972s: 16"}
[2019-02-12 04:53:15,222: INFO/MainProcess] Received task: apiserver.tasks.pow2[f3572ed7-4887-4be2-95a5-0cb42d18e7c5]
[2019-02-12 04:53:15,242: INFO/MainProcess] Received task: apiserver.tasks.pow2[d82648d9-4192-41e7-a018-0a991dd512cb]
[2019-02-12 04:53:15,266: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[d82648d9-4192-41e7-a018-0a991dd512cb] succeeded in 0.011094214s: 9"}
[2019-02-12 04:53:15,290: INFO/MainProcess] Received task: apiserver.tasks.pow2[cb6bbad9-7746-427e-944d-c028cb642408]
[2019-02-12 04:53:15,341: INFO/MainProcess] Received task: apiserver.tasks.pow2[c47e4e1d-3f46-47e4-be38-c2bd54275fd0]
[2019-02-12 04:53:15,394: INFO/MainProcess] Received task: apiserver.tasks.pow2[94b5e9de-0366-454c-82f9-1e4b2c574447]
[2019-02-12 04:53:15,441: INFO/MainProcess] Received task: apiserver.tasks.pow2[f5fba4c2-6033-4f4f-8850-6020678f3c0d]
[2019-02-12 04:53:15,487: INFO/MainProcess] Received task: apiserver.tasks.pow2[6e81897d-3476-4ee9-9313-e1c8b6c387ed]
[2019-02-12 04:53:15,551: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[f3572ed7-4887-4be2-95a5-0cb42d18e7c5] succeeded in 0.324316688999s: 25"}
[2019-02-12 04:53:15,553: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[c47e4e1d-3f46-47e4-be38-c2bd54275fd0] succeeded in 0.196406808001s: 49"}
[2019-02-12 04:53:15,556: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[f5fba4c2-6033-4f4f-8850-6020678f3c0d] succeeded in 0.00907088799977s: 36"}
[2019-02-12 04:53:16,101: WARNING/Worker-12] ---------------------
[2019-02-12 04:53:16,103: WARNING/Worker-12] Total results: 10
[2019-02-12 04:53:16,104: WARNING/Worker-12] FAILED:: 94b5e9de-0366-454c-82f9-1e4b2c574447
[2019-02-12 04:53:16,106: WARNING/Worker-12] Result:: 1
[2019-02-12 04:53:16,107: WARNING/Worker-12] FAILED:: 0bc9e985-8270-43f2-9062-5b61aa409531
[2019-02-12 04:53:16,108: WARNING/Worker-12] Result:: 9
[2019-02-12 04:53:16,110: WARNING/Worker-12] Result:: 16
[2019-02-12 04:53:16,111: WARNING/Worker-12] Result:: 25
[2019-02-12 04:53:16,113: WARNING/Worker-12] Result:: 36
[2019-02-12 04:53:16,114: WARNING/Worker-12] Result:: 49
[2019-02-12 04:53:16,116: WARNING/Worker-12] FAILED:: cb6bbad9-7746-427e-944d-c028cb642408
[2019-02-12 04:53:16,118: WARNING/Worker-12] FAILED:: 6e81897d-3476-4ee9-9313-e1c8b6c387ed
[2019-02-12 04:53:16,127: INFO/MainProcess] {"event": "Task apiserver.tasks.A[6820f648-6e68-4cb8-85e5-0ba996531003] succeeded in 1.216544587s: None"}
[2019-02-12 04:53:16,133: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[0bc9e985-8270-43f2-9062-5b61aa409531] succeeded in 0.00621470599981s: 4"}
[2019-02-12 04:53:16,137: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[cb6bbad9-7746-427e-944d-c028cb642408] succeeded in 0.00544428299872s: 64"}
[2019-02-12 04:53:16,143: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[94b5e9de-0366-454c-82f9-1e4b2c574447] succeeded in 0.00591264000104s: 0"}
[2019-02-12 04:53:16,147: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[6e81897d-3476-4ee9-9313-e1c8b6c387ed] succeeded in 0.00492968600156s: 81"}

```

**Log Sample 2**

```
[2019-02-12 04:51:31,253: INFO/MainProcess] Received task: apiserver.tasks.A[1e5b662d-ea31-4747-a59a-187400641049]
[2019-02-12 04:51:31,463: INFO/MainProcess] Received task: apiserver.tasks.pow2[6bf8f525-8cf1-4cc5-9a9d-7ac5bafdbb89]
[2019-02-12 04:51:31,464: INFO/MainProcess] Received task: apiserver.tasks.pow2[c9e43b7a-cae7-49b4-be3c-3c25d93186f8]
[2019-02-12 04:51:31,579: INFO/MainProcess] Received task: apiserver.tasks.pow2[4f7dc73d-099e-47cb-b49f-d16966d363a5]
[2019-02-12 04:51:31,597: INFO/MainProcess] Received task: apiserver.tasks.pow2[b1f96aaf-b00d-4c3f-a713-60162f835ac2]
[2019-02-12 04:51:31,619: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[6bf8f525-8cf1-4cc5-9a9d-7ac5bafdbb89] succeeded in 0.142188560001s: 4"}
[2019-02-12 04:51:31,637: INFO/MainProcess] Received task: apiserver.tasks.pow2[399a886c-ca22-4ac6-88a4-fef350ae0a50]
[2019-02-12 04:51:31,641: INFO/MainProcess] Received task: apiserver.tasks.pow2[1b771e11-f754-4266-91ee-6318b6f61499]
[2019-02-12 04:51:31,712: INFO/MainProcess] Received task: apiserver.tasks.pow2[0e4b5e77-bb59-4a90-8b65-2dcb611e7955]
[2019-02-12 04:51:31,749: INFO/MainProcess] Received task: apiserver.tasks.pow2[740c3ff5-f313-4e33-a565-9a90ece6d28e]
[2019-02-12 04:51:31,769: INFO/MainProcess] Received task: apiserver.tasks.pow2[ca23a521-903f-4853-b7e3-5d3b377e257d]
[2019-02-12 04:51:31,896: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[b1f96aaf-b00d-4c3f-a713-60162f835ac2] succeeded in 0.27150015s: 49"}
[2019-02-12 04:51:31,898: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[740c3ff5-f313-4e33-a565-9a90ece6d28e] succeeded in 0.108173737s: 64"}
[2019-02-12 04:51:31,900: INFO/MainProcess] Received task: apiserver.tasks.pow2[125dc306-d74a-491a-af07-de1273f6b745]
[2019-02-12 04:51:31,902: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[0e4b5e77-bb59-4a90-8b65-2dcb611e7955] succeeded in 0.111521777s: 25"}
[2019-02-12 04:51:31,905: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[ca23a521-903f-4853-b7e3-5d3b377e257d] succeeded in 0.0646180679996s: 9"}
[2019-02-12 04:51:31,915: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[399a886c-ca22-4ac6-88a4-fef350ae0a50] succeeded in 0.249602029s: 81"}
[2019-02-12 04:51:31,972: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[125dc306-d74a-491a-af07-de1273f6b745] succeeded in 0.0611290939996s: 16"}
[2019-02-12 04:51:32,335: WARNING/Worker-4] ---------------------
[2019-02-12 04:51:32,337: WARNING/Worker-4] Total results: 10
[2019-02-12 04:51:32,339: WARNING/Worker-4] FAILED:: 4f7dc73d-099e-47cb-b49f-d16966d363a5
[2019-02-12 04:51:32,341: WARNING/Worker-4] FAILED:: c9e43b7a-cae7-49b4-be3c-3c25d93186f8
[2019-02-12 04:51:32,343: WARNING/Worker-4] Result:: 4
[2019-02-12 04:51:32,344: WARNING/Worker-4] Result:: 9
[2019-02-12 04:51:32,346: WARNING/Worker-4] Result:: 16
[2019-02-12 04:51:32,347: WARNING/Worker-4] Result:: 25
[2019-02-12 04:51:32,349: WARNING/Worker-4] FAILED:: 1b771e11-f754-4266-91ee-6318b6f61499
[2019-02-12 04:51:32,350: WARNING/Worker-4] Result:: 49
[2019-02-12 04:51:32,352: WARNING/Worker-4] Result:: 64
[2019-02-12 04:51:32,353: WARNING/Worker-4] Result:: 81
[2019-02-12 04:51:32,359: INFO/MainProcess] {"event": "Task apiserver.tasks.A[1e5b662d-ea31-4747-a59a-187400641049] succeeded in 1.102992912s: None"}
[2019-02-12 04:51:32,364: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[c9e43b7a-cae7-49b4-be3c-3c25d93186f8] succeeded in 0.0055113569997s: 1"}
[2019-02-12 04:51:32,369: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[4f7dc73d-099e-47cb-b49f-d16966d363a5] succeeded in 0.00494685999911s: 0"}
[2019-02-12 04:51:32,374: INFO/MainProcess] {"event": "Task apiserver.tasks.pow2[1b771e11-f754-4266-91ee-6318b6f61499] succeeded in 0.00581062799938s: 36"}
```

As you can see in both the samples, the sub-tasks that return a "Failure" result end up returning a value _after_ the results are printed. 
I'm not sure what am I missing here and how to ensure that all sub-tasks return their results accurately.

Thank you so much!

**Comment by auvipy** [comment]
Please try a recent version of celery and report again. 3.x version is not supported
