### ISSUE TITLE
missing parent and children in AsyncResult/GroupResult

### ISSUE THREAD

**Issue by itayB** [celery/celery#5824]
# Checklist

- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

#### Related Issues

- https://github.com/celery/celery/issues/4299
- https://github.com/celery/celery/issues/4516

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce
`celery -A worker worker --loglevel=info`

## Required Dependencies

* **Minimal Python Version**: 3.7.3
* **Minimal Celery Version**: 4.3.0
* **Minimal Kombu Version**: 4.6.3
* **Minimal Broker Version**: amqp==2.5.0 (RabbitMQ 3.7.16)
* **Minimal Result Backend Version**: Redis version=5.0.4
* **Minimal OS and/or Kernel Version**: macOS Mojave 10.14.6
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
aiohttp==3.5.4
amqp==2.5.0
async-timeout==3.0.1
attrs==19.1.0
billiard==3.6.0.0
celery==4.3.0
chardet==3.0.4
idna==2.8
kombu==4.6.3
multidict==4.5.2
pytz==2019.1
redis==3.2.1
vine==1.3.0
yarl==1.3.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```
import time
from celery import Celery, group
from celery.result import AsyncResult, GroupResult


def get_app():
    return Celery(
        'worker',
        broker='pyamqp://localhost/vhost',
        backend='redis://localhost/0'
    )


app = get_app()


@app.task
def add(x, y):
    time.sleep(1)
    return x + y


cf = add.si(0, 0) | group(add.si(1, 1), add.si(2, 2)) | add.si(3, 3)
res = cf.apply_async()

time.sleep(5)  # just in case - wait for the tasks to finish

print(type(res.parent))             # <class 'celery.result.GroupResult'>
print(len(res.parent.children))     # 2
print(type(res.parent.parent))      # <class 'celery.result.AsyncResult'>
print(res.parent.parent.result)     # 0


same_res = AsyncResult(res.id, app=app)
print(type(same_res.parent))             # <class 'NoneType'>
# print(len(same_res.parent.children))     # 'NoneType' object has no attribute 'children'
# print(type(same_res.parent.parent))      # 'NoneType' object has no attribute 'parent'
# print(same_res.parent.parent.result)     # 'NoneType' object has no attribute 'parent'


same_group_res = GroupResult(res.parent.id, app=app)
print(same_group_res.parent)    # None
print(same_group_res.children)  # None
```

</p>
</details>

# Expected & Actual Behavior
I'm trying to build an app that shows canvas flows.
I'm using rabbitMQ as broker and Redis as backend.

Consider the following canvas flow:
`cf = add.si(0, 0) | group(add.si(1, 1), add.si(2, 2)) | add.si(3, 3)`
`res = c1.apply_async()`

Running in debug mode and inspecting `res`, everything looks fine:
res is `AsyncResult` instance of the last task `add.si(3, 3)`, it has no children and its parent is `GroupResult` instance.
Looking in the `GroupResult` children also looks fine, I can see that it has two children - `group(add.si(1, 1)` and `add.si(2, 2)` and its parent is `AsyncResult` instance `add.si(0, 0)`.

Now I expected to see the same behavior when I tried to get the `AsyncResult` object by task_id:
`task_info = AsyncResult(<uuid of task add.si(3, 3)>, app=app)`
Now I see that `task_info.parent` is None.
Why is that?

Looking farther in Flower I can see the `task add.si(3, 3)` parent_id is `add.si(0, 0)` uuid - why is that?

I tried to implement the events loop listener (similar to Flower) and I don't see the `GroupResult` task. Is there a way to see it?
Is it a bug? is it hidden by design? I see in Flower's logs that there's a `celery.group` task. Is there a way to expose it?
```
[I 191107 19:48:36 command:147] Registered tasks:
    ['celery.accumulate',
      'celery.backend_cleanup',
      'celery.chain',
      'celery.chord',
      'celery.chord_unlock',
      'celery.chunks',
      'celery.group',
      'celery.map',
      'celery.starmap']
```

**Comment by itayB** [comment]
also available in SO: https://stackoverflow.com/questions/58779132/missing-parent-and-children-in-asyncresult-groupresult

**Comment by auvipy** [comment]
can you try celery from github master?

**Comment by itayB** [comment]
Hi @auvipy, I checked with version 4.4.0rc3

I ran `pip install https://github.com/celery/celery/zipball/master#egg=celery`:

```
(venv-dev) ~/w/celery-gist $ pip freeze                                                                           08:45:01
amqp==2.5.1
billiard==3.6.1.0
celery==4.4.0rc3
importlib-metadata==0.23
kombu==4.6.5
more-itertools==7.2.0
pytz==2019.3
redis==3.3.11
vine==1.3.0
zipp==0.6.0
```

unfortunately, I get same output :-(

**Comment by auvipy** [comment]
thanks for verifying!

**Comment by itayB** [comment]
I will try to ask it from a different direction: is there an option to reproduce the original canvas flow, assuming I have one of its tasks id?
In addition, I see that **group** task doesn't exist in Redis:
Consider for the following canvas: `add.si(0, 0) | group(add.si(1, 1), add.si(2, 2)) | add.si(3, 3)`
In Redis key: `celery-task-meta-<add.si(0, 0) task id>` children I can see both group task_id and its tasks ids:
```
{

	"status": "SUCCESS",
	"result": 0,
	"traceback": null,
	"children": [
		[
			["a10f2a1f-89a9-4121-b047-0d01d9e0daa0", null],
			[
				[
					["2f015948-cf12-419a-ab45-86518e33cd37", null], null
				],
				[
					["f1687bc3-6846-4273-9ba8-dba8f1d9905b", null], null
				]
			]
		]
	],
	"task_id": "0fcbdc3d-185d-41ce-93c4-0ae8e851bb36",
	"date_done": "2019-11-11T19:45:58.684390"
}
```
But the group's task_id NOT exist in Redis keys (so I cannot figure out who's the group children / chord).
Moreover, if I check the `celery-task-meta-<add.si(3, 3) task id>` key:
```
{
	"status": "SUCCESS",
	"result": 6,
	"traceback": null,
	"children": [],
	"task_id": "070d8d95-2ff4-4e1f-9b2e-905dfba73104",
	"date_done": "2019-11-11T19:46:00.739590",
	"parent_id": "0fcbdc3d-185d-41ce-93c4-0ae8e851bb36"
}
```
As you can see, the `add.si(0, 0)` task_id is set as `add.si(3, 3)` parent's task (instead of the group task_id, `a10f2a1f-89a9-4121-b047-0d01d9e0daa0`).
Does the group task is hidden in purpose? is it supposed to be stored in the backend?

**Comment by bluesurfer** [comment]
Any news on this? I was hoping to implement a monitor on the number of completed tasks over a group but given this issue I am stuck. 

This is the test that fails:

```
import celery
from celery import group
from celery.result import GroupResult


@celery.task()
def add(a, b):
    return a + b


def test_group():
    n = 10
    job = group([add.s(i, i) for i in range(n)])
    r1 = job.apply_async()
    assert len(r1.results) == n

    r2 = GroupResult(id=r1.id)
    assert len(r2.results) == n

```

**Comment by coltonbh** [comment]
Would love to see a clean implementation that solves this! Also mentioned in [#4516](https://github.com/celery/celery/issues/4516) and #4299  

A common use case is when sending celery task id's to clients over HTTP and we need to rehydrate the id's when clients ask for results. The `GroupResult.save()` and `GroupResult.restore()` function have a great API. I'd propose extending these methods to `AsyncResult` and ensure that `.save()` stores the entire task hierarchy for all tasks including chains (i.e., the `GroupResult` may be a group of chains!).

The reason this would be so beneficial is it would make it easy to then call `.forget()` on the rehydrated result and cleanup unneeded results in the database once retrieved by end users. 

## Desired Workflow
```python
# Create initial Celery `Async/GroupResult`

result = task.delay(...) # This may be an `AsyncResult`, `GroupResult`. The `AsyncResult` may have parents, and the `GroupResult.results` may also have parents

result.save()
```

At a later time
```python
result = restore_result(result.id) # Returns either `AsyncResult` or `GroupResult` will full parent/chain hierarchies in tact
```

**Comment by tgross35** [comment]
The current implementation is kind of weird. Why is it that children is always stored but never parent, when both are in the redis db? As an example:

```python
app = Celery("test", backend="redis://", broker="redis://", result_extended=False)
r = redis.Redis(host="localhost")

@app.task(bind=True)
def add(tt, x, y):
    return x + y

seq = (add.s(1,2) | add.s(3) | add.s(4) | add.s(5))()

# See below for result
json.loads(r.get(f'celery-task-meta-{seq.id}').decode('utf8'))

# See below for result
json.loads(r.get(f'celery-task-meta-{seq.parent.parent.parent.id}').decode('utf8'))

# returns None
AsyncResult(seq.id).parent

# Returns a valid AsyncResult
AsyncResult(seq.parent.parent.parent.id).children[0].children[0].children[0]
```

Result of first `json.loads`:
```json
{
  "status": "SUCCESS",
  "result": 15,
  "traceback": null,
  "children": [],
  "date_done": "2022-06-01T00:59:13.397280",
  "parent_id": "2be6a47d-7ba2-4817-a241-83c146fc0e51",
  "task_id": "058e4fac-8a04-4498-9661-17b0d0f8c204"
}
```

Result of the second `json.loads`:
```json
{ 
  "status": "SUCCESS",
  "result": 3,
  "traceback": null,
  "children": [[["b229d016-03f8-489e-ad45-d0e478834bc6", null], null]],
  "date_done": "2022-06-01T00:59:13.376688",
  "task_id": "7731e26c-9351-4088-a4c9-7bc7ef279e0f"
}
```

As this quick test shows, parent_id is available on `seq`'s stored data, so it would make sense to be accessible by `AsyncResult(seq.id).parent`.

I guess that for now, the easiest way to send an entire chain via HTTP is to share the root task ID (accessed via e.g. `parent.parent.parent...`) rather than the lowest-level child, since `.children[0]` will work when `AsyncResult` is loaded via uuid. However, a `GroupResult` doesn't load either `.parent` or `.children`, as was discussed here. This all leaves some questions:

1. Why is `AsyncResult.parent` not available unless specified? This seems like a no-brainer since it's in the backend and "free"
2. Why does `GroupResult` need `.save()` and `.restore()` as mentioned here https://github.com/celery/celery/issues/4516#issuecomment-362428361? It seems like this data should be available without the extra methods

I would suggest making it so that `.parent`, `.children`, and `.results` are always available, if applicable. Some iterators to move up and down in the dependency chain would also be nice. For example:

```python
end = (add.s(1,2) | group(add.s(i) for i in range(4)) | tsum.s() | add.s(4))()
end = Asyncresult(end.id)

for res in end.iter_up():
    # Work up in the dependency graph, save us using .parent.parent
    # res will be an AsyncResult or GroupResult, as applicable
    print(res.id)
    if isinstance(res, GroupResult):
        print(res.results)

for res in end.parent.parent.parent.iter_down():
    # Work down in the dependency graph
    print(res.id)
```

**Comment by tgross35** [comment]
I stand corrected - `.children` is only available to the application after the task is complete (I believe)

**Comment by michaelconan** [comment]
I'm not sure whether this is a related or just somewhat similar issue:

I have a somewhat complex workflow using chain and chords. In the examples above, a group is called within a chain - if I understand [the documentation](https://docs.celeryq.dev/en/stable/userguide/canvas.html#group-callbacks-and-error-handling) correctly, tasks downstream of the group could execute before all of the grouped tasks are finished - therefore I've used chords to control the workflow further.
```python
workflow = chain(
    chord(
        group(preprocess.s(i) for i in range(5)),
        process.s(1),
    ),
    chord(
        group(postprocess.s(i) for i in range(5)),
        chord(
            group(term_upload.s(0), process.s(2)),
            task_report.s(),
        )
    )
).on_error(on_chord_error.s())
result = workflow.apply_async()
```

Upon calling this workflow, I would like to retrieve a complete list of the task IDs by traversing the workflow (ideally names as well).
- I have a function working to get the task names from the workflow variable.
- The `result` variable is an instance of `AsyncResult` for the final task (`task_report`). `result.parent` returns a `GroupResult` for the _first_ group (of `preprocess` tasks), the header of the first chord.

I cannot find any way to traverse from the final result to the results of other tasks in the chain. Is there any way to do this?

**Comment by michaelconan** [comment]
I'm experiencing similar challenges with a somewhat complex chain.

I have multiple layers of parallel (group) processing with a common callback before the next layer, which Celery upgrades to chords.
```python
# Task groups
g1 = group(task1.s(), task2.s(), task3.s())
g2 = group(task4.s(), task5.s(), task6.s())
g3 = group(task7.s(), task8.s(), task9.s())

# Chain workflow
workflow = chain(
    g1, callback1.s(),
    g2, callback2.s(),
    g3, callback3.s(),
).on_error(on_chord_error.s())

# Workflow representation
print(workflow.tasks[0])
```
Each group / task layer is upgraded to a chord, as represented by `workflow.tasks`:
> %(app.callback1([task1(), task2(), task3()]) | %(callback2([task4(), task5(), task6()]) | %(callback3([task7(), task8(), task9()]))))

However, when I call the workflow, I'm unable to traverse the chain to retrieve all of the task IDs:
```python
result = workflow.apply_async()

print(result.id)    # callback3 task
print(result.parent.id)    # g1 group
```

Is there any way to get the task IDs for g2, g3, callback1, callback2?
