### ISSUE TITLE
--autoscale is not working as per the  limitation set.

### ISSUE THREAD

**Issue by theayash** [celery/celery#6015]
# Checklist

- [ T ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ T] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

**Comment by theayash** [comment]
I have set the concurrency max=6 and min=3 but it's going  up-to 10 as per task load.

**Comment by hanchau** [comment]
Please set up monitoring(flower) on you app and share the screenshot of the worker's information when jobs are increasing from 0 to 6 or something.

**Comment by auvipy** [comment]
update? there have been two new updates in autoscale componant on master branch

**Comment by theayash** [comment]
@hanchau Sorry for late reply due to busy schedule. I have already set flower but i don't think you can
get any clue from screenshot to solve the issue but if you still want then i'll share with you in next few days.

**Comment by theayash** [comment]
@auvipy now i am using the updated version (i.e 4.4.2) with default concurrency and i have not tested Autoscaling in this version. Let me check then i'll let you know about the status.
\

**Comment by auvipy** [comment]
and there is also another open PR for autoscale improvement. feel free to review that too.

**Comment by auvipy** [comment]
https://github.com/celery/celery/pull/6085

**Comment by theayash** [comment]
Sure,I'll definitely try to review that because this is very helpful and powerful component of celery. Thanks for letting me know.

**Comment by theayash** [comment]
@auvipy Auto scaling is working as per the limitation set but there is high chance of memory leak and and that leads killing the process for long running task. --max-task-per-child and --max-memory-per-child are not that much efficiently working to control the memory leak and avoid killing a process. Can you please help me out how to deal with it?.

**Comment by auvipy** [comment]
sadly my current focus lies on amqp 1.0 nd billiard 4.0 for celery 4.5. you can tag yourself with the recent contribuotor to autoscae and there is a lined open PR

**Comment by theayash** [comment]
Sure,good luck.

**Comment by auvipy** [comment]
i will get back to autoscale components after those

**Comment by theayash** [comment]
@auvipy One more thing how can we can call one particular task function multiple times simultaneously  with different parameters in django application? Because it's giving me the duplicate data.

**Comment by auvipy** [comment]
can you share code snippets of what you are trying to do?

**Comment by theayash** [comment]
#create_data.py
from faker import Faker
import time
list1 = []
def generate_name(quantity):
    fake = Faker()
    for in in range(quantity):
        name = fake.name()
        list1.append(name)
        time.sleep(2)
    return list1

#task.py
from celery import shared_task
from .create_data import generate_name
@shared_task
def create_task(quantity):   #quantity getting from views.py in django application
    data = generate_name(quantity)
    print(data)

**Comment by theayash** [comment]
@auvipy if am trying to run create_task more than once at same time .....i am getting repeated list  which shouldn't happen.. For every run it should give some different values.!!???

**Comment by theayash** [comment]
If go for random digits also using random module then also it'll give me same set of digits .
