### ISSUE TITLE
Bad file descriptor 

### ISSUE THREAD

**Issue by tarikyayla** [celery/celery#6472]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [x] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:4.4.7 (cliffs) kombu:4.6.11 py:3.7.3
            billiard:3.6.3.0 redis:3.5.3
platform -> system:Darwin arch:64bit
            kernel version:19.6.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://127.0.0.1:6379/6
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
aiohttp==3.6.2
aioredis==1.3.1
amqp==2.6.1
asgiref==3.3.0
async-timeout==3.0.1
asyncio==3.4.3
attrs==19.3.0
billiard==3.6.3.0
bumpversion==0.5.3
celery==4.4.7
certifi==2020.6.20
chardet==3.0.4
click==7.1.2
click-didyoumean==0.0.3
click-repl==0.1.6
contextlib2==0.5.4
coreapi==2.3.3
coreschema==0.0.4
coverage==4.5.4
deepdiff==4.2.0
Django==3.1.3
django-admin-rangefilter==0.6.3
django-autocomplete-light==3.8.1
django-braces==1.4.0
django-crispy-forms==1.9.2
django-datatable==0.2.1
django-easy-select2==1.2.5
django-endless-pagination==2.0
django-filter==2.4.0
django-ipware==1.1.6
django-jsoneditor==0.1.4
django-multiselectfield==0.1.12
django-recaptcha==1.2.1
django-rest-swagger==2.2.0
django-user-agents==0.3.0
djangorestframework==3.12.1
ecdsa==0.13
emoji==0.5.4
et-xmlfile==1.0.1
future==0.18.2
gunicorn==20.0.4
hiredis==1.1.0
httplib2==0.12.1
idna==2.10
importlib-metadata==1.2.0
itypes==1.2.0
jdcal==1.2
Jinja2==2.11.2
jsonfield==1.0.3
kombu==4.6.11
MarkupSafe==1.1.1
more-itertools==8.5.0
multidict==4.7.6
mysqlclient==1.4.2
numpy==1.19.2
oauth2client==4.1.3
oauthlib==1.1.2
openapi-codec==1.3.2
openpyxl==2.3.5
ordered-set==4.0.2
packaging==19.2
pluggy==0.13.1
prompt-toolkit==3.0.8
py==1.9.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pybitbucket==0.11.1
pyparsing==2.4.7
pytest==5.3.1
pytest-cov==2.8.1
pytest-django==3.7.0
python-dateutil==2.8.1
python-gcm==0.4
pytz==2019.3
PyYAML==3.11
raven==6.10.0
redis==3.5.3
requests==2.24.0
requests-oauthlib==0.7.0
rsa==4.0
sentry-sdk==0.14.4
simplejson==3.6.5
six==1.15.0
sqlparse==0.4.1
supervisor==4.1.0
tqdm==4.11.2
typing-extensions==3.7.4.3
tzlocal==1.3
ua-parser==0.10.0
uritemplate==0.6
urllib3==1.25.11
user-agents==2.2.0
vine==1.3.0
wcwidth==0.2.5
yarl==1.6.2
zipp==3.4.0

```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior
```
[2020-11-09 17:06:42,372: ERROR/ForkPoolWorker-5] Task push_notification.tasks.push_queue_task[11af77b3-e848-4dca-86cf-e4fed0b266bb] raised unexpected: OSError(9, 'Bad file descriptor')
Traceback (most recent call last):
  File "/Users/jgtarikyayla/project/venv/lib/python3.7/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/Users/jgtarikyayla/project/venv/lib/python3.7/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/Users/jgtarikyayla/project/push_notification/tasks.py", line 147, in push_queue_task
    loop.run_until_complete(push_main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 571, in run_until_complete
    self.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 1739, in _run_once
    event_list = self._selector.select(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/selectors.py", line 558, in select
    kev_list = self._selector.control(None, max_ev, timeout)
OSError: [Errno 9] Bad file descriptor
```

````
# task.py
@task
def push_queue_task():
    print("Push Service task is received")
    loop = asyncio.get_event_loop()
    loop.run_until_complete(push_main())


@celeryd_init.connect
def push_init(sender=None, conf=None, **kwargs):
    print("Push Service is running")
    push_queue_task.apply_async()
    print("Push Service is started")

async def push_main():
    sem = asyncio.Semaphore(5)
    redis_con = await aioredis.create_redis(address=(settings.REDIS_IP, settings.REDIS_PORT),
                                            db=settings.REDIS_DB,
                                            encoding='utf-8')
    while True:
        redis_pop_data = None

        try:
            with await redis_con as conn:
                queue, redis_pop_data = await conn.blpop(RedisConsts.SERVICE_PUSH)
                push_queue_data = json.loads(redis_pop_data)
                ...
        except Exception as e:
            logging.exception(str(e) + " ,  Data from push queue : " + str(redis_pop_data))

````

Already tried to upgrade celery version, same result.

**Comment by tarikyayla** [comment]
Tried to upgrade Python 3.8.6 and Celery 4.4.7, still not working.

**Comment by tarikyayla** [comment]
`celery -A app_name worker --pool=solo `

Solved my issue. 

https://www.distributedpython.com/2018/10/26/celery-execution-pool/
