### ISSUE TITLE
celery not able to update new value for periodic task

### ISSUE THREAD

**Issue by sheefalis** [celery/celery#6677]
# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [ ] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [ ] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [ ] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [ ] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [ ] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] I have included the contents of ``pip freeze`` in the issue.
- [ ] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [ ] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [ ] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: N/A or Unknown
* **Minimal Celery Version**: N/A or Unknown
* **Minimal Kombu Version**: N/A or Unknown
* **Minimal Broker Version**: N/A or Unknown
* **Minimal Result Backend Version**: N/A or Unknown
* **Minimal OS and/or Kernel Version**: N/A or Unknown
* **Minimal Broker Client Version**: N/A or Unknown
* **Minimal Result Backend Client Version**: N/A or Unknown

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

# Actual Behavior

I am using the celery add_periodic_task function to create two periodic tasks which take an argument on function call, when I call the function the first time it's working perfectly fine (example: printing something every 10 sec ) on the second function call the value has been updated to second and the first function call is not at all working.

Question: How can I keep my first set of periodic task keep running with the addition of a second set
Please find below code : 
**create_app.py :** 
```
from celery import Celery
from celery.schedules import crontab
from flask import Flask
from celery import Celery
from datetime import timedelta

app_c = Flask(__name__)
app_c.config['CELERY_BACKEND'] = "mongodb://127.0.0.1:27017/mycelery"
app_c.config['CELERY_BROKER_URL'] = "mongodb://127.0.0.1:27017/mycelery"
app_c.config['timezone'] = 'UTC'


def make_celery(app_c):
    celery = Celery(app_c.import_name, backend=app_c.config['CELERY_BACKEND'],
                    broker=app_c.config['CELERY_BROKER_URL'])
    celery.conf.update(app_c.config)
    TaskBase = celery.Task

    class ContextTask(TaskBase):
        abstract = True
        def __call__(self, *args, **kwargs):
            with app_c.app_context():
                return TaskBase.__call__(self, *args, **kwargs)
    celery.Task = ContextTask
    return celery

celery_app_c = make_celery(app_c) 
```

**add_periodic.py :** 
```
from flask import Flask
from celery import Celery
from datetime import timedelta
from tasks import poll, send
from create_app import celery_app_c
import time

print(celery_app_c)
def add_task(credential):
    print("in add task")
    celery_app_c.add_periodic_task(10.0,poll.s(credential),name='poll')
    celery_app_c.add_periodic_task(20.0,send.s(credential),name='send')
   




add_task('hello')
time.sleep(20)
add_task('world')
```

**tasks.py:**
```
import time
from celery import Celery
from celery.utils.log import get_task_logger
from create_app import celery_app_c


@celery_app_c.task(name='poll')
def poll(arg):
    content_poll(arg)
    uri_poll(arg)

@celery_app_c.task(name='send')
def send(arg):
    graylog_send(arg)


def content_poll(arg):
    print("polling contens ....",arg)

def uri_poll(arg):
    print("polling uri .....",arg)

def graylog_send(arg):
    print("sending to gl ....... ",arg)

```

running the following code with : **celery -A add_periodic.celery_app_c worker -B --loglevel=INFO**

Note: I need to keep running the periodic task with both set of argument passed 
Please let me know what I am missing here

**Comment by thedrow** [comment]
Please refrain from posting questions on the issue tracker. The mailing list or stack overflow are more appropriate for such questions.

It seems like you are adding the periodic tasks in the Flask process instead of the Celery process.
They don't share a schedule database and therefore the newly added scheduled tasks don't run.

If you need such functionality, please consider using [redbeat](https://github.com/sibson/redbeat).
