### ISSUE TITLE
Cannot communicate with the dockerized workers on mac M1

### ISSUE THREAD

**Issue by cemysf** [celery/celery#6695]
My use case: I have Macbook Pro M1 laptop as my host machine. I want to run celery worker nodes inside linux based docker containers. 

Ubuntu 18.04 as host machine works without any problem, but not the macbook pro with M1 processor. I can create tasks from my host machine, but dockerized workers does not work on anything.

# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussion group](https://groups.google.com/forum/#!forum/celery-users) first.
- [x] I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 5.0.5

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
### host machine
software -> celery:5.0.5 (singularity) kombu:5.0.2 py:3.9.2
            billiard:3.6.3.0 redis:3.5.3
platform -> system:Darwin arch:64bit
            kernel version:20.3.0 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost:6379/0

broker_url: 'redis://localhost:6379/0'
result_backend: 'redis://localhost:6379/0'
deprecated_settings: None
```

```
### inside docker
software -> celery:5.0.5 (singularity) kombu:5.0.2 py:3.9.2
            billiard:3.6.3.0 redis:3.5.3
platform -> system:Linux arch:64bit, ELF
            kernel version:4.19.121-linuxkit imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://host.docker.internal:6379/0

broker_url: 'redis://host.docker.internal:6379/0'
result_backend: 'redis://host.docker.internal:6379/0'
deprecated_settings: None
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.7 or 3.9
* **Minimal Celery Version**: 5.0.5
* **Minimal Kombu Version**: see below
* **Minimal Broker Version**: see below
* **Minimal Result Backend Version**: see below
* **Minimal OS and/or Kernel Version**: see below
* **Minimal Broker Client Version**: see below
* **Minimal Result Backend Client Version**: see below

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
### host machine
amqp==5.0.5
billiard==3.6.3.0
celery @ https://github.com/celery/celery/zipball/master
click==7.1.2
click-didyoumean==0.0.3
click-plugins==1.1.1
click-repl==0.1.6
kombu==5.0.2
prompt-toolkit==3.0.18
pytz==2021.1
redis==3.5.3
six==1.15.0
vine==5.0.0
wcwidth==0.2.5
```

```
### inside docker
amqp==5.0.5
billiard @ https://github.com/celery/billiard/zipball/master
celery @ https://github.com/celery/celery/zipball/master
click==7.1.2
click-didyoumean==0.0.3
click-plugins==1.1.1
click-repl==0.1.6
kombu @ https://github.com/celery/kombu/zipball/master
prompt-toolkit==3.0.18
pytz==2021.1
redis==3.5.3
six==1.15.0
vine @ https://github.com/celery/vine/zipball/master
wcwidth==0.2.5
```
</p>
</details>

### Other Dependencies

<details>
<p>

```
### host machine
% uname -a 
Darwin Ignacios-MBP.fritz.box 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 arm64
```

```
### inside docker
% uname -a
Linux 29461f0a74a4 4.19.121-linuxkit #1 SMP PREEMPT Thu Jan 21 15:45:22 UTC 2021 aarch64 GNU/Linux
```

for redis and docker see test case 0. below
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

0. Host machine setup environment: using redis and docker 
```bash
% redis-server --version
Redis server v=6.2.1 sha=00000000:0 malloc=libc bits=64 build=cfaa1431404ef25b
```

```bash
% docker version
Client: Docker Engine - Community
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.16
 Git commit:        55c4c88
 Built:             Wed Mar  3 00:56:04 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:48 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

1. Run redis-server on host machine
```sh
redis-server --protected mode no --loglevel verbose
```

2. Create a dockerized worker, run it
```python
# tasks.py
from celery import Celery
host = "host.docker.internal"
redis_str = f'redis://{host}:6379/0'
app = Celery('tasks', broker=redis_str, backend=redis_str)
@app.task
def add(x, y):
    return x + y
```

```dockerfile
# Dockerfile
FROM python:3.9
ENV LANG=C.UTF-8 LC_ALL=C.UTF-8 PYTHONUNBUFFERED=1

RUN pip install https://github.com/celery/celery/zipball/master#egg=celery \
 https://github.com/celery/billiard/zipball/master#egg=billiard \
 https://github.com/celery/kombu/zipball/master#egg=kombu \
 https://github.com/celery/vine/zipball/master#egg=vine
RUN pip install redis

COPY . /app
WORKDIR /app
CMD ["celery", "-A", "tasks", "worker", "-l" ,"DEBUG"]
```

```bash
docker build -f Dockerfile -t celery_dockerized .
docker run celery_dockerized
```

2. Setup host machine celery, change `host="localhost"` for the host machine in tasks.py
```bash
python3 -m venv venv  # tried with python 3.7 and 3.9
source venv/bin/activate
pip install https://github.com/celery/celery/zipball/master#egg=celery \
 https://github.com/celery/billiard/zipball/master#egg=billiard \
 https://github.com/celery/kombu/zipball/master#egg=kombu \
 https://github.com/celery/vine/zipball/master#egg=vine
pip install redis  
```

```python
# tasks.py
from celery import Celery
host = "localhost"
redis_str = f'redis://{host}:6379/0'
app = Celery('tasks', broker=redis_str, backend=redis_str)
@app.task
def add(x, y):
    return x + y
```

3. Trigger the task from host machine, it will give the task id
```bash
% celery -A tasks call --args='[1,2]' tasks.add

<some_task_id>
```

</p>
</details>

# Expected Behavior

Dockerized containers (linux) take and execute tasks that are initiated from host machine (mac m1).

# Actual Behavior

Dockerized containers (linux) does not take any tasks that are initiated from host machine (mac m1). Also, they also cannot see any other worker nodes on host machine. But, they can see other worker nodes within the docker container. There are no error/warning messages on celery workers. 

- Redis server logs, when a dockerized worker created
```
18405:M 24 Mar 2021 17:13:05.576 - DB 0: 2 keys (0 volatile) in 8 slots HT.
18405:M 24 Mar 2021 17:13:09.565 - Accepted 192.168.64.6:57300
18405:M 24 Mar 2021 17:13:09.566 - Accepted 192.168.64.6:57302
18405:M 24 Mar 2021 17:13:10.740 - DB 0: 2 keys (0 volatile) in 8 slots HT.
18405:M 24 Mar 2021 17:13:14.581 - Accepted 192.168.64.6:57304
18405:M 24 Mar 2021 17:13:14.615 - Accepted 192.168.64.6:57306
18405:M 24 Mar 2021 17:13:14.619 - Accepted 192.168.64.6:57308
18405:M 24 Mar 2021 17:13:15.648 - Accepted 192.168.64.6:57310
18405:M 24 Mar 2021 17:13:15.654 - Accepted 192.168.64.6:57312
18405:M 24 Mar 2021 17:13:15.663 - Accepted 192.168.64.6:57314
18405:M 24 Mar 2021 17:13:15.669 - Accepted 192.168.64.6:57316
18405:M 24 Mar 2021 17:13:15.678 - Accepted 192.168.64.6:57318
18405:M 24 Mar 2021 17:13:15.717 * 100 changes in 300 seconds. Saving...
```

- Worker node running inside docker, when a task created from host machine nothing happens. Or, when there is a new worker on host machine also nothing..
```
[2021-03-24 15:29:12,402: INFO/MainProcess] Connected to redis://host.docker.internal:6379/0
[2021-03-24 15:29:12,402: DEBUG/MainProcess] ^-- substep ok
[2021-03-24 15:29:12,403: DEBUG/MainProcess] | Consumer: Starting Events
[2021-03-24 15:29:12,424: DEBUG/MainProcess] ^-- substep ok
[2021-03-24 15:29:12,424: DEBUG/MainProcess] | Consumer: Starting Mingle
[2021-03-24 15:29:12,425: INFO/MainProcess] mingle: searching for neighbors
[2021-03-24 15:29:13,463: INFO/MainProcess] mingle: all alone
[2021-03-24 15:29:13,463: DEBUG/MainProcess] ^-- substep ok
[2021-03-24 15:29:13,463: DEBUG/MainProcess] | Consumer: Starting Gossip
[2021-03-24 15:29:13,477: DEBUG/MainProcess] ^-- substep ok
[2021-03-24 15:29:13,478: DEBUG/MainProcess] | Consumer: Starting Tasks
[2021-03-24 15:29:13,485: DEBUG/MainProcess] ^-- substep ok
[2021-03-24 15:29:13,485: DEBUG/MainProcess] | Consumer: Starting Control
[2021-03-24 15:29:13,494: DEBUG/MainProcess] ^-- substep ok
[2021-03-24 15:29:13,494: DEBUG/MainProcess] | Consumer: Starting Heart
[2021-03-24 15:29:13,500: DEBUG/MainProcess] ^-- substep ok
[2021-03-24 15:29:13,501: DEBUG/MainProcess] | Consumer: Starting event loop
[2021-03-24 15:29:13,501: DEBUG/MainProcess] | Worker: Hub.register Pool...
[2021-03-24 15:29:13,501: INFO/MainProcess] celery@d03f98ad699a ready.
```

- Same worker node above, when another one created in the same docker container, or inside a new container. Also, it runs tasks that are triggered inside the same or other container just fine.
```
[2021-03-24 15:45:40,711: DEBUG/MainProcess] pidbox received method hello(from_node='celery@10dde1c3db69', revoked={}) [reply_to:{'exchange': 'reply.celery.pidbox', 'routing_key': 'acf00853-a0b7-3d14-bb4d-92295b74b1b8'} ticket:3bc055e9-d508-4f18-add5-bf80ffb83aa9]
[2021-03-24 15:45:40,711: INFO/MainProcess] sync with celery@10dde1c3db69
[2021-03-24 15:45:41,765: DEBUG/MainProcess] celery@10dde1c3db69 joined the party
```

**Comment by thedrow** [comment]
This is likely to be a deployment problem rather than a bug report.
Do you have any evidence to suggest otherwise?

**Comment by cemysf** [comment]
Well, is there any celery cli commands that I could try to get more info? I'm not quite sure how to continue/where to look into

**Comment by thedrow** [comment]
If localhost gives you a task id, you probably have redis running locally.

**Comment by cemysf** [comment]
it was a deployment error indeed, hard reset solved the problem, thanks anyway
