### ISSUE TITLE
Serialization error on retry with `ignore_result=False`

### ISSUE THREAD

**Issue by stsewd** [celery/celery#7455]
# Checklist

- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [ x I have read the relevant section in the
  [contribution guide](http://docs.celeryproject.org/en/latest/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [x] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [x] I have tried reproducing the issue on more than one operating system.
- [x] I have tried reproducing the issue on more than one workers pool.
- [x] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- None

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**:

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
software -> celery:5.2.5 (dawn-chorus) kombu:5.2.4 py:3.10.1
            billiard:3.6.4.0 redis:4.2.2
platform -> system:Linux arch:64bit, ELF
            kernel version:5.16.18-200.fc35.x86_64 imp:CPython
loader   -> celery.loaders.app.AppLoader
settings -> transport:redis results:redis://localhost/

broker_url: 'redis://localhost:6379//'
result_backend: 'redis://localhost/'
deprecated_settings: None
result_serializer: 'json'
```

</p>
</details>

# Steps to Reproduce

## Required Dependencies

* **Minimal Python Version**: 3.x
* **Minimal Celery Version**: >=4.x (haven't tried with 3.x)
* **Minimal Kombu Version**: N/A
* **Minimal Broker Version**: N/A
* **Minimal Result Backend Version**: N/A
* **Minimal OS and/or Kernel Version**: N/A
* **Minimal Broker Client Version**: N/A
* **Minimal Result Backend Client Version**: N/A

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==5.1.0
async-timeout==4.0.2
attrs==21.4.0
billiard==3.6.4.0
-e git+ssh://git@github.com/celery/celery.git@de65e6abbdf4a863bcbbe70912af2b76c6f53d87#egg=celery
click==8.1.2
click-didyoumean==0.3.0
click-plugins==1.1.1
click-repl==0.2.0
Deprecated==1.2.13
iniconfig==1.1.1
kombu==5.2.4
packaging==21.3
pluggy==1.0.0
prompt-toolkit==3.0.29
py==1.11.0
pyparsing==3.0.8
pytest==7.1.1
pytz==2022.1
redis==4.2.2
six==1.16.0
tomli==2.0.1
vine==5.0.0
wcwidth==0.2.5
wrapt==1.14.0
```

</p>
</details>

### Other Dependencies

<details>
<p>
N/A
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
# tasks.py
from celery import Celery

app = Celery('tasks', broker='redis://localhost', backend='redis://localhost')
app.conf.result_serializer = 'json'

@app.task(bind=True, ignore_result=False, max_retries=1)
def add(self, retry):
    if retry:
        self.retry(exc=TypeError)
    raise TypeError
```

```python
import pytest
from tasks import add

if __name__ == "__man__":
    # This is okay
    r = add.delay(False)
    with pytest.raises(TypeError):
        r.get()

    # This returns kombu.exceptions.EncodeError: TypeError('Object of type type is not JSON serializable')
    r = add.delay(True)
    with pytest.raises(TypeError):
        r.get()

```

</p>
</details>

# Expected Behavior

Raising an exception directly or via retry should have the same behavior. 

# Actual Behavior

Raising an exception directly seems to work, but when using retry
there is a serialization error

```
kombu.exceptions.EncodeError: TypeError('Object of type type is not JSON serializable')
```

If this is expected, maybe a mention of this behavior on the docs would be great. Thanks for this amazing project!

**Comment by stsewd** [comment]
> which celery version you are using? 5.2.6?

I was able to replicate with master, 5.x and 4.x
