### ISSUE TITLE
Rejected task in task_prerun signal gets executed in celery 4 and further

### ISSUE THREAD

**Issue by parthpandya** [celery/celery#7792]
Hi! I see that despite rejecting the task in celery signal handler `@signals.task_prerun.connect`, the task goes on and executes in celery 4 (4.4.7) and further. 
Whereas, this was not the case in celery 3.
The same code attached below could be tried and run in both celery versions. 

# Checklist

- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [ ] This has already been asked to the [discussions forum](https://github.com/celery/celery/discussions) first.
- [x] I have read the relevant section in the
  [contribution guide](https://docs.celeryq.dev/en/master/contributing.html#other-bugs)
  on reporting bugs.
- [x] I have checked the [issues list](https://github.com/celery/celery/issues?q=is%3Aissue+label%3A%22Issue+Type%3A+Bug+Report%22+-label%3A%22Category%3A+Documentation%22)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22PR+Type%3A+Bugfix%22+-label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/master)
  to find out if the bug was already fixed in the master branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

## Mandatory Debugging Information

- [x] I have included the output of ``celery -A proj report`` in the issue.
    (if you are not able to do this, then at least specify the Celery
     version affected).
- [ ] I have verified that the issue exists against the `master` branch of Celery.
- [x] I have included the contents of ``pip freeze`` in the issue.
- [x] I have included all the versions of all the external dependencies required
  to reproduce this bug.

## Optional Debugging Information

- [x] I have tried reproducing the issue on more than one Python version
  and/or implementation.
- [ ] I have tried reproducing the issue on more than one message broker and/or
  result backend.
- [ ] I have tried reproducing the issue on more than one version of the message
  broker and/or result backend.
- [ ] I have tried reproducing the issue on more than one operating system.
- [ ] I have tried reproducing the issue on more than one workers pool.
- [ ] I have tried reproducing the issue with autoscaling, retries,
  ETA/Countdown & rate limits disabled.
- [x] I have tried reproducing the issue after downgrading
  and/or upgrading Celery and its dependencies.

#### Related Issues

- https://github.com/celery/celery/issues/4222 (Maybe related)

#### Possible Duplicates

- None

## Environment & Settings

**Celery version**: 4.4.7

<details>
<summary><b><code>celery report</code> Output:</b></summary>
<p>

```
Connected to amqp://guest:**@127.0.0.1:5672//
mingle: searching for neighbors
mingle: all alone
celery@myhost.local ready.
Received task: tasks.test_reject[fa586c07-0fd2-4e90-9531-a38c051b56eb]  
task pre run handler called
Signal handler <function task_prerun_handler at 0x101f51048> raised: reject requeue=False: test reject
Traceback (most recent call last):
  File "/Users/path/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/path/celeryRejectTest/celeryconfig.py", line 18, in task_prerun_handler
    raise Reject("test reject", requeue=False)
celery.exceptions.Reject: ('test reject', False)
ADD task result: 5

```

</p>
</details>

# Steps to Reproduce

**send.py**
```
from tasks import test_reject
test_reject.apply_async(queue='add', args=[2,3])
```

**celeryconfig.py**
```
from kombu import Exchange, Queue
from celery import signals
from celery.exceptions import Reject

# queue configuration
task_queues = [
    Queue('add', Exchange('add'), routing_key='add'),
]
worker_prefetch_multiplier=1

# Signal Handlers

@signals.task_prerun.connect
def task_prerun_handler(sender, **named):
    print("task pre run handler")
    raise Reject("test reject", requeue=False)
```

**celery_base.py**
```
from celery import Celery

app = Celery('celery_base',
             broker='pyamqp://guest@localhost//',
            include=['tasks'])

app.config_from_object('celeryconfig')

```

**tasks.py**
```
import time
from celery_base import app

@app.task(acks_late=True)
def test_reject(x, y):
    time.sleep(2)
    print("ADD task result: {}".format(x+y))
```

## Required Dependencies

* **Minimal Python Version**: 2.7 AND 3.5.10
* **Minimal Celery Version**: 4.4.7
* **Minimal Kombu Version**: 4.6.11
* **Minimal Broker Version**: 3.5.10 RabbitMQ
* **Minimal Result Backend Version**: N/A
* **Minimal OS and/or Kernel Version**: N/A
* **Minimal Broker Client Version**: N/A
* **Minimal Result Backend Client Version**: N/A

### Python Packages

<details>
<summary><b><code>pip freeze</code> Output:</b></summary>
<p>

```
amqp==2.6.1
billiard==3.6.4.0
celery==4.4.7
certifi==2022.5.18
chardet==4.0.0
docutils==0.18.1
Embedly==0.5.0
evernote3==1.25.14
Geohash==1.0
httplib2==0.20.4
idna==2.10
importlib-metadata==2.1.3
kombu==4.6.11
oauth2==1.9.0.post1
oauthlib==3.1.0
pyparsing==2.4.7
python-geohash==0.8.5
pytz==2022.1
requests==2.25.1
requests-oauthlib==1.3.1
six==1.16.0
urllib3==1.26.9
vine==1.3.0
zipp==1.2.0

```

</p>
</details>

### Other Dependencies

<details>
<p>
Celery version 4.4.7
</p>
</details>

## Minimally Reproducible Test Case

<details>
<p>

```python
```

</p>
</details>

# Expected Behavior

Task rejected in celery signal handler `@signals.task_prerun.connect` should not get executed/run. 

Celery 3 has this expectation working fine.

# Actual Behavior

Task rejected in `@signals.task_prerun.connect` gets executed in celery 4. This should not be the case.

```
Signal handler <function task_prerun_handler at 0x101f51048> raised: reject requeue=False: re-queued on throttled queue
Traceback (most recent call last):
  File "/Users/path/python3.5/site-packages/celery/utils/dispatch/signal.py", line 288, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/Users/path/celeryRejectTest/celeryconfig.py", line 18, in task_prerun_handler
    raise Reject("re-queued on throttled queue", requeue=False)
celery.exceptions.Reject: ('test reject', False)
[2022-10-06 16:34:47,902: WARNING/ForkPoolWorker-1] ADD task result: 5 # NOTICE THE REJECTED TASK STILL GETS EXECUTED
```

**Comment by parthpandya** [comment]
@hankehly Thanks for trying it out. The task still goes on to get executed as per what I have seen. I was using versions below:
Celery: 3.1.25
Python 2.7.18
RabbitMQ: 3.8.34

**Comment by auvipy** [comment]
I would interested to have any sort of fix/contributions for this. but with appropriate tests as well

**Comment by Udit107710** [comment]
Why is this decision taken? Is that a design choice to facilitate a feature or something?

**Comment by charlottemrd** [comment]
Have you find a by pass to this problem ? I am also impacted by that. I have upgraded my project from celery 3 to celery 5, and I am facing this issue
