### ISSUE TITLE
Object of type AsyncResult is not JSON serializable to revoke a task in Celery 5.2.6

### ISSUE THREAD

**Issue by alimp5** [celery/celery#8020]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Category%3A+Documentation%22+)
  for similar or identical bug reports.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?q=is%3Apr+label%3A%22Category%3A+Documentation%22)
  for existing proposed fixes.
- [x] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the bug was already fixed in the main branch.
- [x] I have included all related issues and possible duplicate issues in this issue
      (If there are none, check this box anyway).

# Description

I followed Celery doc to learn and revoke my Python Django task(s) then terminate it by doc's examples:
https://docs.celeryq.dev/en/stable/userguide/workers.html?highlight=revoke#revoke-revoking-tasks

But my tests were failed and don't work.
I want to stop and kill a task by task-id in python django.
Python: 3.8.10
Django: 4.0.4
Celery: 5.2.6
OS:  windows 10 - 64 bit (latest build)

### celery.py:
```
import os, redis
from celery import Celery

client = redis.Redis(host='localhost', port=6379, db=0, decode_responses=True)
for key in client.keys('celery-task-meta-*'):
    client.delete(key)


os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'ea_games.settings')

celery_app = Celery('ea_games')
celery_app.config_from_object('django.conf:settings', namespace='CELERY')
celery_app.control.discard_all()
celery_app.control.purge()
celery_app.autodiscover_tasks()

BASE_REDIS_URL = os.environ.get('REDIS_URL', 'redis://localhost:6379')
celery_app.conf.broker_url = BASE_REDIS_URL

celery_app.control.discard_all()
celery_app.control.purge()
```

### settings.py:
```
CELERY_BROKER_URL = 'redis://localhost:6379'
CELERY_RESULT_BACKEND = 'redis://localhost:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Tehran'
CELERY_REDIRECT_STDOUTS_LEVEL = 'INFO'
```

### tasks.py:
```
@shared_task(name="sum x+y")
def sum_xy (x, y):
    print (f"inside task_id: {str(sum_xy.request.id)}")
    print (f"SUM 1: {x+y}")
    time.sleep(999)
    print (f"SUM 2: {x+y}")

task_id = sum_xy.delay(5, 2)
print (f"outside task_id: {task_id}")
#celery_app.control.revoke(task_id)
#AsyncResult({"id": task_id}).revoke(terminate=True)
AsyncResult(id).revoke(terminate=True)
```

### tasks.py (error):
```
(ea_env) PS F:\ea_env\ea_games> celery -A ea_games worker -l info -P eventlet
outside task_id: e8b29e7f-abc2-47a0-990d-1ffa191f442e
outside task_id: 8230a96e-4a58-4b54-be8b-3c06ee1512c7
Traceback (most recent call last):
  File "F:\ea_env\lib\site-packages\kombu\serialization.py", line 39, in _reraise_errors
    yield
  File "F:\ea_env\lib\site-packages\kombu\serialization.py", line 210, in dumps
    payload = encoder(data)
  File "F:\ea_env\lib\site-packages\kombu\utils\json.py", line 68, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "C:\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "F:\ea_env\lib\site-packages\kombu\utils\json.py", line 58, in default
    return super().default(o)
  File "C:\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type AsyncResult is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\ea_env\Scripts\celery.exe\__main__.py", line 7, in <module>
  File "F:\ea_env\lib\site-packages\celery\__main__.py", line 15, in main
    sys.exit(_main())
  File "F:\ea_env\lib\site-packages\celery\bin\celery.py", line 217, in main
    return celery(auto_envvar_prefix="CELERY")
  File "F:\ea_env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "F:\ea_env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "F:\ea_env\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "F:\ea_env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "F:\ea_env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "F:\ea_env\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "F:\ea_env\lib\site-packages\celery\bin\base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
  File "F:\ea_env\lib\site-packages\celery\bin\worker.py", line 343, in worker
    worker = app.Worker(
  File "F:\ea_env\lib\site-packages\celery\worker\worker.py", line 94, in __init__
    self.app.loader.init_worker()
  File "F:\ea_env\lib\site-packages\celery\loaders\base.py", line 111, in init_worker       
    self.import_default_modules()
  File "F:\ea_env\lib\site-packages\celery\loaders\base.py", line 105, in import_default_modules
    raise response
  File "F:\ea_env\lib\site-packages\celery\utils\dispatch\signal.py", line 276, in send     
    response = receiver(signal=self, sender=sender, **named)
  File "F:\ea_env\lib\site-packages\celery\fixups\django.py", line 82, in on_import_modules 
    self.worker_fixup.validate_models()
  File "F:\ea_env\lib\site-packages\celery\fixups\django.py", line 120, in validate_models  
    self.django_setup()
  File "F:\ea_env\lib\site-packages\celery\fixups\django.py", line 116, in django_setup     
    django.setup()
  File "F:\ea_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "F:\ea_env\lib\site-packages\django\apps\registry.py", line 116, in populate
    app_config.import_models()
  File "F:\ea_env\lib\site-packages\django\apps\config.py", line 304, in import_models      
    self.models_module = import_module(models_module_name)
  File "C:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "F:\ea_env\ea_games\ea_app\models.py", line 23, in <module>
    from ea_app.all_utils.ea_utils import FULL_REQUEST_CLASS, proxy_manager_func
  File "F:\ea_env\ea_games\ea_app\all_utils\ea_utils.py", line 19, in <module>
    from ea_app import tasks
  File "F:\ea_env\ea_games\ea_app\tasks.py", line 66, in <module>
    AsyncResult({"id": task_id}).revoke(terminate=True)
  File "F:\ea_env\lib\site-packages\celery\result.py", line 160, in revoke
    self.app.control.revoke(self.id, connection=connection,
  File "F:\ea_env\lib\site-packages\celery\app\control.py", line 496, in revoke
    return self.broadcast('revoke', destination=destination, arguments={
  File "F:\ea_env\lib\site-packages\celery\app\control.py", line 741, in broadcast
    return self.mailbox(conn)._broadcast(
  File "F:\ea_env\lib\site-packages\kombu\pidbox.py", line 335, in _broadcast
    self._publish(command, arguments, destination=destination,
  File "F:\ea_env\lib\site-packages\kombu\pidbox.py", line 303, in _publish
    producer.publish(
  File "F:\ea_env\lib\site-packages\kombu\messaging.py", line 166, in publish
    body, content_type, content_encoding = self._prepare(
  File "F:\ea_env\lib\site-packages\kombu\messaging.py", line 254, in _prepare
    body) = dumps(body, serializer=serializer)
  File "F:\ea_env\lib\site-packages\kombu\serialization.py", line 210, in dumps
    payload = encoder(data)
  File "C:\Python38\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "F:\ea_env\lib\site-packages\kombu\serialization.py", line 43, in _reraise_errors    
    reraise(wrapper, wrapper(exc), sys.exc_info()[2])
  File "F:\ea_env\lib\site-packages\kombu\exceptions.py", line 21, in reraise
    raise value.with_traceback(tb)
  File "F:\ea_env\lib\site-packages\kombu\serialization.py", line 39, in _reraise_errors    
    yield
  File "F:\ea_env\lib\site-packages\kombu\serialization.py", line 210, in dumps
    payload = encoder(data)
  File "F:\ea_env\lib\site-packages\kombu\utils\json.py", line 68, in dumps
    return _dumps(s, cls=cls or _default_encoder,
  File "C:\Python38\lib\json\__init__.py", line 234, in dumps
    return cls(
  File "C:\Python38\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Python38\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "F:\ea_env\lib\site-packages\kombu\utils\json.py", line 58, in default
    return super().default(o)
  File "C:\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
kombu.exceptions.EncodeError: Object of type AsyncResult is not JSON serializable


```

**Comment by alimp5** [comment]
i found a similar issue:

https://github.com/celery/celery/issues/7529

**Comment by paradox-lab** [comment]
You should pass the argument of str(task_id) instead of task_id to AsyncResult.

```python
AsyncResult(str(task_id)).revoke(terminate=True)
```

**Comment by alimp5** [comment]
@paradox-lab 
I will check and tell you. Tnx ;X

**Comment by auvipy** [comment]
what is the status of the issue? did you check?

**Comment by alimp5** [comment]
@auvipy
I will check. plz plz be patient. TNX a lot ;X (up to the next 3 days)

**Comment by auvipy** [comment]
OK. and also check with celery 5.3.x
