### ISSUE TITLE
Priority tasks SQS

### ISSUE THREAD

**Issue by Scolymus** [celery/celery#8129]
# Checklist

- [x] I have checked the [issues list](https://github.com/celery/celery/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3A%22Issue+Type%3A+Feature+Request%22+)
  for similar or identical feature requests.
- [x] I have checked the [pull requests list](https://github.com/celery/celery/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3A%22PR+Type%3A+Feature%22+)
  for existing proposed implementations of this feature.
- [ ] I have checked the [commit log](https://github.com/celery/celery/commits/main)
  to find out if the same feature was already implemented in the
  main branch.
- [x] I have included all related issues and possible duplicate issues
  in this issue (If there are none, check this box anyway).

#### Related Issues

- None

#### Possible Duplicates

- None

# Brief Summary

I want to use a priority queue with SQS. Right now, I understand this is only working with RabbitMQ. In Rabbit, task priority is being inserted by using "priority" arg in apply_async. Same applies with Redis, although is not really a priority as in RabbitMQ.
SQS does not have any avalaible option.

# Design

## Architectural Considerations

I was thinking that as a I way of inserting this in SQS we could define a list of brokerurls, where each url is a queue in SQS, and give a number (E.g, url1 (high priority) is 0, url2 (medium priority) is 1, url3 (low priority) is 2. Then the only necessary is to define which broker url to use when sending task, and to check first the brokerurls list in a specific order (check url0, if no message => check url 1 and so...).

## Diagrams

N/A

## Alternatives

None

**Comment by Amwam** [comment]
In case this is useful, I've been able to create a prototype of task priorities, by overriding the Celery Task, and injecting the desired queue during `apply_async()`

This allows me to use a `priority=` kwarg on the task definition. If the priority is not available in `_QUEUES`, it will fall back to the configured default queue.

This could also be achieved by supplying the queue name in the task definition, however this method allows us to use the same configuration for different broker types, without having to change all existing tasks

```python
from celery import Task, Celery

# Task priority number to SQS queue name
_QUEUES = {
    10: "high-celery-broker-queue",
    5: "medium-celery-broker-queue",
    1: "low-celery-broker-queue",
}


class CeleryPriorityTask(Task):
    def apply_async(self, *args, **kwargs):
        # Adjust the queue based on the priority
        if priority := kwargs.get("priority"):
            if queue := _QUEUES.get(priority):
                kwargs["queue"] = queue

        return super().apply_async(*args, **kwargs)

# Load Celery configuration
celery_app = Celery(
    "my.celery.module",  task_cls=CeleryPriorityTask
)
```
